export const creatorsDB = [
  {
    image: "Egg1.svg",
    artist: "Ralph Edwards",
    price: "0.69",
    name: "Canapé#4",
    id: "1",
  },
  {
    image: "Egg2.svg",
    artist: "Jane Cooper",
    price: "0.29",
    name: "Canapé#4",
    id: "2",
  },
  {
    image: "Hat1.svg",
    artist: "Ralph Edwards",
    price: "0.39",
    name: "Canapé#66",
    id: "3",
  },
  {
    image: "Egg3.svg",
    artist: "Jane Cooper",
    price: "0.340",
    name: "Canapé#67",
    id: "4",
  },
  {
    image: "Egg4.svg",
    artist: "Ralph Edwards",
    price: "0.30",
    name: "Canapé#898",
    id: "5",
  },
  {
    image: "Hat3.svg",
    artist: "Jane Cooper",
    price: "0.70",
    name: "Canapé#5764",
    id: "6",
  },
  {
    image: "Hat4.svg",
    artist: "Ralph Edwards",
    price: "0.02",
    name: "Caneré#45",
    id: "7",
  },
  {
    image: "Hat2.svg",
    artist: "Jane Cooper",
    price: "0.349",
    name: "Canapé#467",
    id: "8",
  },
  {
    image: "Egg1.svg",
    artist: "Ralph Edwards",
    price: "0.4",
    name: "Canapé#467",
    id: "9",
  },
  {
    image: "Egg2.svg",
    artist: "Jane Cooper",
    price: "0.3456",
    name: "Canapé#4567",
    id: "10",
  },
  {
    image: "Egg3.svg",
    artist: "Ralph Edwards",
    price: "0.4",
    name: "Canapé#467",
    id: "11",
  },
  {
    image: "Egg4.svg",
    artist: "Jane Cooper",
    price: "0.3456",
    name: "Canapé#4567",
    id: "12",
  },
];
